(display "Scheme.NET REPL v0.1")
(display #\newline)
(display #\newline)
(define repl-env (scheme-report-environment 5))
(define repl
  (lambda (e)
    (display "-> ")
    (let ((r (read)))
	  (display "=> ")
      (display (eval r e))
      (display #\newline)
    )
    (repl e)
  )
)
(repl repl-env)